'use client';

import Link from 'next/link';
import { ChevronDown, ChevronUp } from 'lucide-react';
import { useState } from 'react';

// FAQ categories and questions
const faqCategories = [
  {
    title: 'Getting Started',
    questions: [
      {
        question: 'What is an AI-powered digital content generator?',
        answer: 'Our AI-powered digital content generator is a platform that uses artificial intelligence to transform your product images and information into professional marketing assets optimized for digital signage, social media, and other digital platforms. It automates the creation of visually appealing content with consistent branding and proper formatting for different platforms.'
      },
      {
        question: 'How do I get started with the platform?',
        answer: 'Getting started is easy! Simply sign up for an account, choose a subscription plan (or start with our free trial), upload your product images and information, select your desired output formats, and let our AI generate professional digital content for you. Check out our detailed [Getting Started Guide](/documentation/getting-started-guide) for step-by-step instructions.'
      },
      {
        question: 'Do I need design skills to use this platform?',
        answer: 'No design skills are required! Our AI handles all the design work based on your inputs and preferences. You simply provide your product images and information, and our system automatically creates professionally designed marketing content for you.'
      },
      {
        question: 'What kind of results can I expect?',
        answer: 'You can expect professional-quality digital marketing content that\'s optimized for the platforms you choose. Our AI generates visually appealing designs that maintain your brand identity while highlighting your products effectively. Check out our [Case Studies](/case-studies) page to see real-world examples.'
      },
    ]
  },
  {
    title: 'Platform & Features',
    questions: [
      {
        question: 'What platforms and formats are supported?',
        answer: 'We support a wide range of digital platforms including digital signage systems, Instagram, TikTok, Facebook, Twitter, LinkedIn, and more. Our system automatically optimizes content for each platform\'s specific requirements, including aspect ratios, text limitations, and visual best practices.'
      },
      {
        question: 'Can I customize the generated content?',
        answer: 'Yes! While our AI automates the design process, you have multiple customization options. You can adjust brand colors, fonts, logo placement, messaging emphasis, and more. The Professional and Enterprise plans offer more advanced customization capabilities.'
      },
      {
        question: 'How does batch processing work?',
        answer: 'Batch processing allows you to upload multiple products at once and generate content for your entire catalog efficiently. Simply upload a spreadsheet with your product information along with the corresponding images, and our system will process them all, maintaining consistent branding across all generated content.'
      },
      {
        question: 'Can I integrate this with my existing marketing tools?',
        answer: 'Yes, our platform offers multiple integration options. The Professional and Enterprise plans include direct publishing to social media platforms, and the Enterprise plan includes API access for custom integrations with your existing marketing workflow tools. Check our [Integrations](/integrations) page for more details.'
      }
    ]
  },
  {
    title: 'Content & Usage Rights',
    questions: [
      {
        question: 'Who owns the content generated by the platform?',
        answer: 'You own all rights to the content generated using our platform, subject to your subscription terms. The content is created based on your inputs and for your exclusive use.'
      },
      {
        question: 'Can I use the generated content for commercial purposes?',
        answer: 'Yes, all content generated on our platform can be used for commercial purposes. There are no restrictions on how you use the outputs in your marketing efforts.'
      },
      {
        question: 'Are there limits to how many pieces of content I can generate?',
        answer: 'Yes, each subscription plan comes with a monthly limit on the number of content pieces you can generate. The Starter plan includes 50 generations per month, Professional includes 200 per month, and Enterprise offers unlimited generations. You can also purchase additional generations if needed.'
      },
      {
        question: 'What happens to my original images and data?',
        answer: 'Your original images and data remain yours. We store them securely to provide the service and do not use your content to train our AI without explicit permission. Please see our [Privacy Policy](/privacy) for complete details on how we handle your data.'
      }
    ]
  },
  {
    title: 'Technical & Support',
    questions: [
      {
        question: 'What image specifications do you recommend?',
        answer: 'For best results, we recommend uploading high-quality product images with a minimum resolution of 1080px on the shortest side. Transparent backgrounds (PNG format) work best for products, but our system can also process images with backgrounds. See our [Image Requirements](/documentation/image-requirements) guide for detailed specifications.'
      },
      {
        question: 'How quickly does the AI generate content?',
        answer: 'Most individual content pieces are generated within 30-60 seconds. Batch processing times depend on the number of items and complexity but typically process at a rate of 1-2 minutes per item. Our system handles the queue efficiently to maximize throughput.'
      },
      {
        question: 'What if I\'m not satisfied with the generated content?',
        answer: 'You can regenerate content with different parameters if you\'re not satisfied with the initial results. Our platform also learns from your preferences over time. If you need assistance, our support team is available to help optimize your results.'
      },
      {
        question: 'What kind of support is available?',
        answer: 'The level of support depends on your subscription plan. All plans include access to our knowledge base and community forums. The Professional plan includes priority email support, while Enterprise customers enjoy dedicated account management and phone support.'
      }
    ]
  },
  {
    title: 'Billing & Accounts',
    questions: [
      {
        question: 'Can I cancel my subscription at any time?',
        answer: 'Yes, you can cancel your subscription at any time. When you cancel, you\'ll maintain access to the service until the end of your current billing period. There are no cancellation fees.'
      },
      {
        question: 'Is there a free trial available?',
        answer: 'Yes, we offer a 14-day free trial that includes 20 content generations so you can experience the full capabilities of our platform before committing to a subscription.'
      },
      {
        question: 'How do I upgrade or downgrade my plan?',
        answer: 'You can upgrade your plan at any time, and the changes will take effect immediately. Downgrades will take effect at the start of your next billing cycle. Simply go to the Account Settings > Subscription section to make these changes.'
      },
      {
        question: 'Do you offer discounts for annual subscriptions?',
        answer: 'Yes, we offer a 20% discount when you subscribe annually instead of monthly. This option is available for all our pricing tiers.'
      }
    ]
  }
];

export default function FAQPage() {
  const [openCategory, setOpenCategory] = useState(0);
  const [openQuestions, setOpenQuestions] = useState<Record<string, boolean>>({});

  const toggleCategory = (index: number) => {
    setOpenCategory(openCategory === index ? -1 : index);
  };

  const toggleQuestion = (catIndex: number, qIndex: number) => {
    const key = `${catIndex}-${qIndex}`;
    setOpenQuestions({
      ...openQuestions,
      [key]: !openQuestions[key]
    });
  };

  return (
    <div className="bg-white">
      {/* Header */}
      <div className="bg-blue-600">
        <div className="px-4 py-16 mx-auto max-w-7xl sm:py-24 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold tracking-tight text-center text-white">Frequently Asked Questions</h1>
          <p className="max-w-3xl mx-auto mt-6 text-xl text-center text-blue-100">
            Find answers to common questions about our AI-powered digital content generator.
          </p>
        </div>
      </div>

      {/* FAQ Content */}
      <div className="px-4 py-16 mx-auto max-w-7xl sm:px-6 lg:py-24 lg:px-8">
        <div className="max-w-3xl mx-auto divide-y-2 divide-gray-200">
          <div className="divide-y divide-gray-200">
            {faqCategories.map((category, catIndex) => (
              <div key={catIndex} className="py-6">
                <button
                  onClick={() => toggleCategory(catIndex)}
                  className="flex justify-between items-center w-full text-left"
                >
                  <h3 className="text-xl font-semibold text-gray-900">{category.title}</h3>
                  <span>
                    {openCategory === catIndex ? (
                      <ChevronUp className="h-6 w-6 text-blue-600" />
                    ) : (
                      <ChevronDown className="h-6 w-6 text-gray-400" />
                    )}
                  </span>
                </button>
                
                {openCategory === catIndex && (
                  <div className="mt-4 space-y-6">
                    {category.questions.map((faq, qIndex) => (
                      <div key={qIndex} className="border-b border-gray-100 pb-6 last:border-b-0 last:pb-0">
                        <button
                          onClick={() => toggleQuestion(catIndex, qIndex)}
                          className="flex justify-between items-start w-full text-left"
                        >
                          <h4 className="text-lg font-medium text-gray-900">{faq.question}</h4>
                          <span className="ml-6 flex-shrink-0">
                            {openQuestions[`${catIndex}-${qIndex}`] ? (
                              <ChevronUp className="h-5 w-5 text-blue-600" />
                            ) : (
                              <ChevronDown className="h-5 w-5 text-gray-400" />
                            )}
                          </span>
                        </button>
                        
                        {openQuestions[`${catIndex}-${qIndex}`] && (
                          <div 
                            className="mt-2 text-base text-gray-600"
                            dangerouslySetInnerHTML={{
                              __html: faq.answer.replace(
                                /\[([^\]]+)\]\(([^)]+)\)/g,
                                '<a href="$2" class="text-blue-600 hover:text-blue-500">$1</a>'
                              )
                            }}
                          />
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Still have questions section */}
      <div className="bg-gray-50">
        <div className="px-4 py-16 mx-auto max-w-7xl sm:px-6 lg:py-24 lg:px-8">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900">Still have questions?</h2>
            <p className="mt-4 text-lg text-gray-500">
              Can't find the answer you're looking for? Please contact our support team.
            </p>
            <div className="flex flex-col items-center justify-center mt-8 space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
              <Link 
                href="/contact" 
                className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700"
              >
                Contact Support
              </Link>
              <Link 
                href="/documentation" 
                className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-blue-600 bg-white border border-blue-600 rounded-md shadow-sm hover:bg-blue-50"
              >
                Browse Documentation
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 